FROM ruby:2.2.2
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
RUN mkdir /rails_app
WORKDIR /rails_app
ADD . /rails_app
RUN bundle install
ENTRYPOINT rm -rf /rails_app/tmp; \
           bundle exec rake initdb:run RAILS_ENV=production; \
           bundle exec rake assets:precompile; \
           bundle exec rails s -p 3000 -b '0.0.0.0' -e production
