nginx:
  build: ./docker/nginx/development/
  ports:
    - "8080:80"
  links:
    - web
db:
  build: ./docker/postgres/development/
web:
  build: .
  dockerfile: ./Dockerfile.development
  volumes:
    - .:/rails_app
  ports:
    - "3000:3000"
  links:
    - db
